services:
    db:
      image: mariadb:latest
      ports:
        - "3306:3306"
      healthcheck:
        test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
        start_period: 10s
        interval: 10s
        timeout: 5s
        retries: 3
      environment:
        MARIADB_ROOT_PASSWORD: GoodTime221
        MARIADB_DATABASE: flow_manage
    app:
        build:
          context: .
        ports:
            - "8100:8100"
            - "4848:4848"
        depends_on:
            db:
              condition: service_healthy
        healthcheck:
          test: [ "CMD", "./asadmin", "--user=admin", "--passwordfile=/opt/payara/passwordfile", "list-applications", "|", "grep", "-q", "FlowManageMaven" ]
          interval: 30s
          timeout: 10s
          retries: 3