services:
    db:
      image: mariadb:latest
      ports:
        - "3306:3306"
      healthcheck:
        test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
        start_period: 10s
        interval: 10s
        timeout: 5s
        retries: 3
      environment:
        MARIADB_ROOT_PASSWORD: password # Change this to a secure password
        MARIADB_DATABASE: flow_manage
    app:
        build:
          context: .
        ports:
            - "8100:8100"
            - "4848:4848"
        depends_on:
            db:
              condition: service_healthy