package com.model.pojo;
// Generated Sep 30, 2024 4:01:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name="project"
    ,catalog="flow_manage"
)
public class Project  implements java.io.Serializable {


     private Integer id;
     private Status status;
     private String title;
     private String overview;
     private Date deadline;
     private int priority;
     private Set<ProjectWorker> projectWorkers = new HashSet<ProjectWorker>(0);

    public Project() {
    }

    // Test
    public Project(Project other) {
        this.id = other.id;
        this.status = other.status;
        this.title = other.title;
        this.overview = other.overview;
        this.deadline = other.deadline;
        this.priority = other.priority;
        this.projectWorkers = new HashSet<ProjectWorker>(other.projectWorkers);
    }
	
    public Project(Status status, String title, String overview, Date deadline, int priority) {
        this.status = status;
        this.title = title;
        this.overview = overview;
        this.deadline = deadline;
        this.priority = priority;
    }
    public Project(Status status, String title, String overview, Date deadline, int priority, Set<ProjectWorker> projectWorkers) {
       this.status = status;
       this.title = title;
       this.overview = overview;
       this.deadline = deadline;
       this.priority = priority;
       this.projectWorkers = projectWorkers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity = Status.class)
    @JoinColumn(name="status_id", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="overview", nullable=false, length=65535)
    public String getOverview() {
        return this.overview;
    }
    
    public void setOverview(String overview) {
        this.overview = overview;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="deadline", nullable=false, length=10)
    public Date getDeadline() {
        return this.deadline;
    }
    
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    
    @Column(name="priority", nullable=false)
    public int getPriority() {
        return this.priority;
    }
    
    public void setPriority(int priority) {
        this.priority = priority;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="project", targetEntity = ProjectWorker.class, cascade = CascadeType.ALL)
    public Set<ProjectWorker> getProjectWorkers() {
        return this.projectWorkers;
    }
    
    public void setProjectWorkers(Set<ProjectWorker> projectWorkers) {
        this.projectWorkers = projectWorkers;
    }
    
}


