package com.model.pojo;
// Generated Sep 30, 2024 4:01:08 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProjectWorkerId generated by hbm2java
 */
@Embeddable
public class ProjectWorkerId  implements java.io.Serializable {


     private int userId;
     private int projectId;

    public ProjectWorkerId() {
    }

    public ProjectWorkerId(int userId, int projectId) {
       this.userId = userId;
       this.projectId = projectId;
    }
   


    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


    @Column(name="project_id", nullable=false)
    public int getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProjectWorkerId) ) return false;
		 ProjectWorkerId castOther = ( ProjectWorkerId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getProjectId()==castOther.getProjectId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getProjectId();
         return result;
   }   


}


